### ISSUE TITLE
Administration Discord Bot

### ISSUE THREAD

**Issue by DLmass** [carlodrift/skoice#29]
I don't understand why the discord bot needs server administrator for it to be able to work. This needs to be looked into so the discord bot can be limited. I tried to make it work without the administrator permissions but the bot won't function properly. Most of my bots on my server don't need administrator to work properly and in that way I can limit where they belong and what they do in case the bot which belongs to the account is hacked, so they cannot delete the Discord server.

**Comment by carlodrift** [comment]
The bot code is open-source and is executed by your Minecraft server, so no worries there. Moreover, we ask for Administrator permissions to ensure smooth operation on all servers regardless of their specificities. Besides, only the owner of the server can remove it. I think your problem is not related to permissions, from what I saw on Discord. I invite you to continue this discussion on the Discord server

**Comment by carlodrift** [comment]
As mentioned, we can't remove the administrator permission because Skoice wouldn't work without it.
However, Skoice is a self-hosted solution, with your own bot running on your own server with open-source Skoice code. Nobody can access your bot but you.
Note that if Skoice commands bother you in certain channels or for certain users, you can configure permissions for this in the integration settings (Discord Server Settings).
